### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by jeremiah-gaiser** [INFO-526-S24/project-01-Datatude-dynamos#1]
The following is the peer review of the project proposal by GraphCrafters. The team members that participated in this review are 

- Anjani Sowmya Bollapragada - @asbollapragada
- Omid Zandi - @zandi-omid
- Jeremiah Gaiser - @jeremiah-gaiser
- Surajit Pal - @sura789
- Mrunal Ravindra Jadhav - @mrunal0699
- Praveen Kumar Pappala - @Praveen Kumar Pappala

**- Describe the goal of the project.**
Assess how US politics and external world events such as COVID-19, military conflicts, and other sources of instability affect the spatial distribution of the flow of refugees over time, as well as identify general trends in refugee dynamics more broadly. 

**- Describe the data used or collected.**
The primary dataset contains refugee statistics for each year between 2010 and 2022. Columns include country of origin, country of asylum, number of refugees, number of asylum seekers and number of returned refugees, number of stateless persons, and other such data. Additionally, they intend to collect data from external sources in order to quantify US policy and world events. 

**- Describe how the research question will be answered, e.g. what approaches / methods will be used.**
Data on US foreign policy and internal politics will be used in conjunction with time series analysis of refugee movement to assess the impact of US politics on refugee patterns and the displacement of peoples abroad. Similar techniques will be used with data that corresponds to world events, such as 'conflict histories, records of climate events, economic indicators, and epidemic timelines.'   

**- Is there anything that is unclear from the proposal?**
The provenance and structure of the US political data is not entirely clear. How will "shifts in foreign policy" be quantified? 

For both questions 1 and 2, it is not entirely clear what techniques the team intends to use to relate the external and primary data. 

While the analyses sound very interesting, descriptions of neither question 1 or 2 provide the reader with an idea of what the final visualization will actually look like.  

**- Provide constructive feedback on how the team might be able to improve their project.**
Rather than vague allusions to identifying trends in the data, provide a more fleshed-out description of how you expect to relate the various data, and what form the final visualization might take. Will you be making use of a heatmap  over a geographical map, or are the trends of interest better elucidated by a more traditional scatter plot? 

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
Very interested in how US foreign policy affects refugee dynamics, and how that will be quantified. 

**- Provide constructive feedback on any issues with file and/or code organization.**
No code yet provided.

**- (Optional) Any further comments or feedback?**
This is a super interesting and ambitious project! Sincerely excited to see the final result.

**Comment by zeuszapper** [comment]
We appreciate you taking the time to look over our project proposal and for your informative and helpful criticism. We greatly appreciate your recommendations for improving our analytical techniques and determining the influence of outside variables. Without a doubt, we'll focus on the plots which you mentioned  and  the other 2 questions  as you advised. We are thrilled to apply your insights into our project and appreciate your encouragement. Again, I appreciate your insightful advice. We liked your those feedback and working on it.

The  **Primary**  question you raised was  **The provenance and structure of the US political data is not entirely clear. How will shifts in foreign policy be quantified?** 

**Our Take**:  We were intended to discuss this at first, but we haven't settled on the specifics. Based on the working model, we thought we would add or remove some restrictions, but we haven't determined on the reason for doing so. However, for the time being, we would like to draw attention to this. I appreciate you drawing attention to this, and I really appreciate your desire and interest in our project. The procedure proceeds in this manner :
  

1. Legislative acts or executive orders that impact refugee admissions.
2. Allocations of refugee quotas.
3. Changes in the processing speed or criteria for refugee applications.
4. Public statements or policies reflecting a change in stance towards refugees.

### Quantify foreign policy shifts by:

Creating a Timeline:  We will Mark periods of Democratic and Republican administrations and annotate it with major foreign policy changes affecting refugees.

Policy Change Indicators: We will Develop indicators such as "policy restrictiveness" based on the nature and impact of each policy change. This might involve coding policies on a scale (e.g., from "expansive" to "restrictive").

Event Markers: Indicate periods of significant external factors (major weather events, COVID-19 pandemic onset, and key developments).
 
**The event markers is tenetative constraint .**


### The Visualization  we are working to implement  : 

1. [ ] Timelines of administrations, policy changes, and significant external events.
2. [ ] Trends in refugee admissions over time.
3. [ ] Comparative analysis of different administrations and the impact of policy shifts.


Again Thank You,
Best Regards
Datatude-dynamos Team.
