### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by mohit-taparia** [INFO-526-S24/project-01-Datatude-dynamos#2]
The following is the peer review of the project proposal by Team Crimson. 
The team members that participated in this review are 

- Mohit Rakesh Taparia] - @mohit-taparia
- Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj
- Arun Koundinya Parasa - @ArunKoundinya
- Pradnya Ramesh Raut - @PradnyaR24
- Varun Soni - @solitudevedhas
- 
- Describe the goal of the project.
The project aims to analyze global refugee trends between 2010 and 2022, exploring the impact of external factors on refugee movements. It seeks to identify correlations, patterns, and drivers behind refugee flows, offering insights for policymakers and humanitarian efforts.

- Describe the data used or collected.
The data used for analysis is sourced from the {refugees} R package, encompassing information on displaced populations from UNHCR, UNRWA, and IDMC between 2010 and 2022. This dataset includes refugees, asylum seekers, internally displaced people, stateless individuals, and other groups, with detailed records categorized by year, quantitative metrics, and origin/asylum countries with corresponding codes. With 64,809 rows, the dataset offers comprehensive insights into global migration dynamics over a decade.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The first question is about examining the evolution of refugee population patterns over time and assess the influence of American political party stances on these changes, particularly concerning refugee migrations towards the United States. This question basically aims to explore how changes in refugee populations have been influenced by the stances of American political parties.  An external data on US foreign policy changes, political party statements is being used to understand influence of US political parties. Utilizing time series analysis, the research evaluates shifts in refugee populations over time, integrating external data on US foreign policy changes and political events to assess their correlation with refugee trends. By contextualizing findings within US political timelines and policy shifts, the study seeks to quantify the impact of political dynamics on refugee patterns.

Now the Second question focuses on exploring the fluctuations in refugee populations worldwide, aiming to understand the impact of external factors such as economics, conflict, and climate change. Through analysis of variables like 'year', 'coo_name' (destination country), 'coa_name' (asylum country), and 'refugees', we aim to untangle the complexities of global migration by normalizing refugee data against population statistics and employing time-series techniques, we will identify trends associated with significant global occurrences such as wars, climate disasters, and economic changes. Integration of external data, encompassing conflict histories, climate events, economic indicators, and epidemic timelines, will provide essential context to discern the diverse influences shaping global refugee movements.

- Is there anything that is unclear from the proposal?
The proposal is well-organized. However, here are a few things that are unclear from the proposal.
1. Clarification on the specific methods and techniques to be used for data analysis, such as the selection of statistical models or software tools.
2. Further elaboration on how the external factors, such as war, climate change, and financial stability, will be quantitatively assessed for their impact on refugee populations.
3. A more detailed explanation of how the normalization of refugee data against population statistics will be conducted and its implications for the analysis.
4. Consideration of potential limitations or biases in the dataset and how these will be addressed in the analysis and interpretation of results.

- Provide constructive feedback on how the team might be able to improve their project.
Clarify specific research objectives and hypotheses for each question to ensure focused analysis. Also, consider incorporating qualitative methods or case studies to deepen understanding of refugee motivations and experiences.
Apart from that ensure rigorous data cleaning and validation procedures to address any inconsistencies or missing data in the dataset and expand the discussion on potential limitations of the analysis, including biases in the dataset and external factors not accounted for.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested in exploring the correlation between wars and conflicts and refugee migration patterns over time, particularly focusing on the duration of involvement in wars and their impact on refugee movements. By analyzing data on wars, conflicts, and refugee numbers across nations, we can gain insights into the complex relationship between geopolitical events and refugee flows. This analysis will help to understand humanitarian consequences of conflicts and help inform policies aimed at addressing refugee crises globally, resulting in understanding the causes of displacement and the influence of external factors on patterns of displacement throughout the last ten years.

- Provide constructive feedback on any issues with file and/or code organization.
More code commendation would be nice to see so that we know the details of what is occurring. Also, the author's name or team name is absent in the proposal. It would be preferable to mention the data source in the introduction, providing a hyperlink to the tidy source dataset.

- (Optional) Any further comments or feedback?
Good job on the project. All the best.

**Comment by ayeshakhatunsujana** [comment]
We appreciate you taking the time to look over our project proposal and for your informative and helpful criticism. We greatly appreciate your recommendations for improving our analytical techniques and determining the influence of outside variables. Without a doubt, we'll focus on outlining how we address data biases and limits and adding additional comments to our code to make it clearer. We shall make a point of emphasizing the connection between refugee migrations and wars in our presentation, as you advised. We are thrilled to apply your insights into our project and appreciate your encouragement. Again, I appreciate your insightful advice. We liked your those feedback and working on it.

> Clarification on the specific methods and techniques to be used for data analysis, such as the selection of statistical models or software tools.

> Further elaboration on how the external factors, such as war, climate change, and financial stability, will be quantitatively assessed for their impact on refugee populations.

> A more detailed explanation of how the normalization of refugee data against population statistics will be conducted and its implications for the analysis.

> Consideration of potential limitations or biases in the dataset and how these will be addressed in the analysis and interpretation of results.

Again Thank You, 
Best Regards
Datatude-dynamos Team
