### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-S24/project-01-Datatude-dynamos#3]
Dear Datatude dynamos: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |    3    |
| Proposal | 5         |     4.5   |
| Workflow | 1         |    1    |
| Teamwork | 1         |    1    |
| Total    | 10        |    9.5    |

**Overall**
Very nice work! Only relatively minor issues. It looks like you didn't suppress messages... I also would like to see a timeline showing when you expect each stage of the project to be finished.

**Comment by Gchism94** [comment]
You probably don't need one, but if you would like a regrade, please address and resubmit your proposal by **Monday, Feb 19th, 11:59pm**.

**Procedure**

1. Close this issue.
2. Open a new blank one requesting a regrade

Your final score will be the midpoint between the two scores.

**Comment by zeuszapper** [comment]
Thank You ! , for you're valuable feedback Professor .
